version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 10.3 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme bigmac2

  build:
    macos:
      xcode: 10.3 # indicate your selected version of Xcode
    steps:
      - checkout
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r bigmac2app.zip build/Release/bigmac2.app
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/artifacts/
          path: bigmac2app.zip
          destination: app

workflows:
  test_build:
    jobs:
      - test
      - build:
          requires: # sequence the build job to run after test
          - test
